### ISSUE TITLE
The flag for Afghanistan is out-of-date

### ISSUE THREAD

**Issue by jpmckinney** [hampusborgos/country-flags#136]
Wikipedia has the new version: https://en.wikipedia.org/wiki/Flag_of_Afghanistan

**Comment by wyattoday** [comment]
Thanks for letting me know. I was waiting for the new flag after the government collapse.

I haven’t dug into it yet, but are there primary sources for the new flag (laws, edicts, etc.)? Because Wikipedia tends to make shit up, and it’s better to have a legit source so that flag can be fixed to be accurate.

**Comment by jpmckinney** [comment]
I haven’t done the research - Wikipedia cites The Flag Bulletin journal.

**Comment by wyattoday** [comment]
The current occupying forces are not recognized as a government (by any other government in the world). And there are at least 3 competing "official" flags by the occupying force.

While I agree the collapsed government flag is likely obsolete, until there is a recognized government with an official flag, putting anything else there is reckless.

I'm going to close this, but I encourage anyone to re-open when a stable government is created and a flag is decided upon.
