### ISSUE TITLE
License absent

### ISSUE THREAD

**Issue by tieugene** [hampusborgos/country-flags#90]
And these flags can't be redistributble in OSS

**Comment by JimmyCushnie** [comment]
Please search before creating an issue. #32 #76 #72 #56 #50

**Comment by JimmyCushnie** [comment]
@wyattoday honestly maybe you should add a note about this to the readme so people stop asking

**Comment by tieugene** [comment]
> @wyattoday honestly maybe you should add a note about this to the readme so people stop asking

There is a note about this in REAME ("The flags are not under copyright protection...") but no one pruf.
Another side that many distros (like RH-based) _require_  to specify directly. And include license text in source.
So I cannot write "License: the author says everything will ok" in package.

**Comment by hampusborgos** [comment]
@tieugene Problem is, you cannot include flags carte-blanche, for example here is the list of laws in the US for the US flag:

(a)The flag should never be displayed with the union down, except as a signal of dire distress in instances of extreme danger to life or property.
(b)The flag should never touch anything beneath it, such as the ground, the floor, water, or merchandise.
(c)The flag should never be carried flat or horizontally, but always aloft and free.
(d)The flag should never be used as wearing apparel, bedding, or drapery. It should never be festooned, drawn back, nor up, in folds, but always allowed to fall free. Bunting of blue, white, and red, always arranged with the blue above, the white in the middle, and the red below, should be used for covering a speaker’s desk, draping the front of the platform, and for decoration in general.
(e)The flag should never be fastened, displayed, used, or stored in such a manner as to permit it to be easily torn, soiled, or damaged in any way.
(f)The flag should never be used as a covering for a ceiling.
(g)The flag should never have placed upon it, nor on any part of it, nor attached to it any mark, insignia, letter, word, figure, design, picture, or drawing of any nature.
(h)The flag should never be used as a receptacle for receiving, holding, carrying, or delivering anything.
(i)The flag should never be used for advertising purposes in any manner whatsoever. It should not be embroidered on such articles as cushions or handkerchiefs and the like, printed or otherwise impressed on paper napkins or boxes or anything that is designed for temporary use and discard. Advertising signs should not be fastened to a staff or halyard from which the flag is flown.
(j)No part of the flag should ever be used as a costume or athletic uniform. However, a flag patch may be affixed to the uniform of military personnel, firemen, policemen, and members of patriotic organizations. The flag represents a living country and is itself considered a living thing. Therefore, the lapel flag pin being a replica, should be worn on the left lapel near the heart.
(k)The flag, when it is in such condition that it is no longer a fitting emblem for display, should be destroyed in a dignified way, preferably by burning.


Other countries have similar, looong lists. It must be up to user of this library that he/she does not present it upside down, any license for this would be over 100 pages with rules!

**Comment by tieugene** [comment]
> @tieugene Problem is, you cannot include flags carte-blanche, for example here is the list of laws in the US for the US flag:
> 
> > (a) The flag should never be ...

Ok, replace "The flag" with "_image_ of flag".
It is not flag itself.

**Comment by hampusborgos** [comment]
> > @tieugene Problem is, you cannot include flags carte-blanche, for example here is the list of laws in the US for the US flag:
> > > (a) The flag should never be ...
> 
> Ok, replace "The flag" with "_image_ of flag".
> It is not flag itself.

I would argue that "The flag should never be used for advertising purposes in any manner whatsoever" for example, would not be encompassed by a public domain license. If the image of the flag from this repository is used in an advertising campaign, it would certainly by a violation of this law.
